# .github/workflows/windows-arm64-exe.yml
name: Windows ARM64 Build (Fast EXE)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh   # use PowerShell everywhere

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.18.1

    - name: Install dependencies
      run: npm ci

    - name: Build React
      run: npm run buildreact

    - name: Compile source
      run: npm run compile

    # 🔑 fast packaging target that creates ../VSCode-win32-arm64/Code.exe
    - name: Package for Windows ARM64
      run: npm run gulp vscode-win32-arm64-build-quick

    - name: Zip packaged folder
      run: |
        Compress-Archive -Path ../VSCode-win32-arm64/* -DestinationPath void-win32-arm64.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: void-win32-arm64
        path: |
          ../VSCode-win32-arm64/
          void-win32-arm64.zip
