# .github/workflows/windows-arm64-exe.yml
name: Windows ARM64 EXE Build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    defaults: { run: { shell: pwsh } }

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4
      with: { node-version: 20.18.1 }

    - name: Install dependencies
      run: npm ci

    - name: Build React
      run: npm run buildreact

    - name: Compile source
      run: npm run compile

    # ▶ 1. Package – this creates  …\VSCode-win32-arm64\Code.exe
    - name: Package for Windows ARM64
      run: npm run gulp vscode-win32-arm64-build

    # ▶ 2. Move package **into the workspace** (avoids using “..” later)
    - name: Move packaged folder inside workspace
      run: Move-Item -Path ..\VSCode-win32-arm64 -Destination $Env:GITHUB_WORKSPACE\VSCode-win32-arm64

    # ▶ 3. Zip the folder
    - name: Zip packaged folder
      run: Compress-Archive -Path VSCode-win32-arm64\* -DestinationPath void-win32-arm64.zip

    # ▶ 4. Upload artifacts: runnable folder + zip
    - uses: actions/upload-artifact@v4
      with:
        name: void-win32-arm64
        path: |
          VSCode-win32-arm64/
          void-win32-arm64.zip

